HrTool.WEB/Models/CreateEmployeeBenefitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HrTool.WEB.Models
{
    public class CreateEmployeeBenefitViewModel
    {
        public string EmployeeId { get; set; }
        public string EmployeeBenefitId { get; set; }
    }
}

HrTool.WEB/Models/DeleteDepartmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HrTool.WEB.Models
{
    public class DeleteDepartmentViewModel
    {
        public string DepartmentId { get; set; }
        public string Name { get; set; }
    }
}

HrTool.WEB/Controllers/RegistryController.cs
using HrTool.BLL;
using HrTool.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HrTool.WEB.Controllers
{
    public class RegistryController : Controller
    {
        private readonly IDepartmentService _departmentService;
        private readonly IEmployeeService _employeeService;
        private readonly IEmployeeBenefitService _employeeBenefitService;

        public RegistryController()
        {
            _departmentService = new DepartmentService();
            _employeeService = new EmployeeService();
            _employeeBenefitService = new EmployeeBenefitService();
        }

        // GET: Registry
        public ActionResult ListDepartments()
        {
            var employees = _employeeService.GetAllEmployees();
            var myDepartments = _departmentService.GetAllDepartments();
            var listOfDepartment = myDepartments.Select(x => new DepartmentViewModel
            {
                DepartmentId = x.DepartmentId,
                EmployeeId = x.EmployeeId,
                EmployeeDisplayName = BuildDisplayNameForDepartmentManager(employees, x),
                DepartmentEmail = x.DepartmentEmail,
                Name = x.Name
            });
            return View(listOfDepartment);
        }

        // GET:
        // CREATE Department
        public ActionResult CreateDepartment()
        {
            var employees = _employeeService.GetAllEmployees();
            var model = new DepartmentViewModel
            {
                Employees = new List<SelectListItem>()
            };
            foreach (var item in employees)
            {
                model.Employees.Add(new SelectListItem
                {
                    Text = item.PersonalDetails.FirstName + " " + item.PersonalDetails.LastName,
                    Value = item.EmployeeId
                });
            }
            return View(model);
        }
        // POST:
        // CREATE Department

        [HttpPost]
        public ActionResult CreateDepartment(DepartmentViewModel department)
        {

            _departmentService.CreateDepartment(new Domain.Department
            {
                EmployeeId = department.EmployeeId,
                DepartmentEmail = department.DepartmentEmail,
                Name = department.Name

            });

            return RedirectToAction("ListDepartments");
        }

        //EDIT DEPARTMENT
        public ActionResult UpdateDepartment(string id)
        {
            var myDepartment = _departmentService.GetDepartmentById(id);
            var employees = _employeeService.GetAllEmployees();
            var departmentToUpdate = new DepartmentViewModel
            {
                DepartmentId = myDepartment.DepartmentId,
                Name = myDepartment.Name,
                DepartmentEmail = myDepartment.DepartmentEmail,
                EmployeeId = myDepartment.EmployeeId,
                Employees = new List<SelectListItem>()
            };

            foreach (var item in employees)
            {
                departmentToUpdate.Employees.Add(new SelectListItem
                {
                    Text = item.PersonalDetails.FirstName + " " + item.PersonalDetails.LastName,
                    Value = item.EmployeeId,
                    Selected = item.EmployeeId == myDepartment.EmployeeId
                });

            }

            return View(departmentToUpdate);
        }

        //EDIT DEPARTMENT
        [HttpPost]
        public ActionResult UpdateDepartment(DepartmentViewModel department)
        {
            var myDepartment = _departmentService.GetDepartmentById(department.DepartmentId);
            myDepartment.EmployeeId = department.EmployeeId;
            myDepartment.Name = department.Name;
            myDepartment.DepartmentEmail = department.DepartmentEmail;

            _departmentService.UpdateDepartment(myDepartment);
            return RedirectToAction("ListDepartments", new { id = department.DepartmentId });

        }

        //DELETE
        public ActionResult DeleteDepartment(string id)
        {
            var myDepartment = _departmentService.GetDepartmentById(id);
            var departmentToDelete = new DeleteDepartmentViewModel
            {
                DepartmentId = myDepartment.DepartmentId,
                Name = myDepartment.Name
            };
            return View(departmentToDelete);
        }

        //DELETE
        [HttpPost]
        public ActionResult DeleteDepartment(string id, FormCollection formcollection)
        {
            _departmentService.DeleteDepartment(id);
            return RedirectToAction("ListDepartments");
        }



        private string BuildDisplayNameForDepartmentManager(IList<Domain.Employee> employees, Domain.Department department)
        {
            var employee = employees.First(x => x.EmployeeId == department.EmployeeId);
            return employee.PersonalDetails.FirstName + " " + employee.PersonalDetails.LastName;
        }

        //*************************************************************************************************

        //LIST EMPLOYEE BENEFITS
        public ActionResult ListEmployeeBenefits()
        {
            var myEmployeeBenefits = _employeeBenefitService.GetAllEmployeeBenefits();

            var listOfEmployeeBenefits = myEmployeeBenefits.Select(x => new EmployeeBenefitViewModel
            {
                EmployeeBenefitId = x.EmployeeBenefitId,
                Name = x.Name,
                Description = x.Description
            });
            return View(listOfEmployeeBenefits);
        }

        // CREATE EMPLOYEE BENEFIT
        public ActionResult CreateEmployeeBenefit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateEmployeeBenefit(EmployeeBenefitViewModel employeeBenefit)
        {

            _employeeBenefitService.CreateEmployeeBenefit(new Domain.EmployeeBenefit
            {
                Name = employeeBenefit.Name,
                Description = employeeBenefit.Description

            });

            return RedirectToAction("ListEmployeeBenefits");
        }

        //EDIT EMPLOYEE BENEFIT
        public ActionResult UpdateEmployeeBenefit(string id)
        {
            var myEmployeeBenefit = _employeeBenefitService.GetEmployeeBenefitById(id);

            var EmployeeBenefitToUpdate = new EmployeeBenefitViewModel
            {
                EmployeeBenefitId = myEmployeeBenefit.EmployeeBenefitId,
                Name = myEmployeeBenefit.Name,
                Description = myEmployeeBenefit.Description
            };

            return View(EmployeeBenefitToUpdate);
        }

        //EDIT EMPLOYEE BENEFIT
        [HttpPost]
        public ActionResult UpdateEmployeeBenefit(EmployeeBenefitViewModel employeeBenefit)
        {
            var myEmployeeBenefit = _employeeBenefitService.GetEmployeeBenefitById(employeeBenefit.EmployeeBenefitId);

            myEmployeeBenefit.Name = employeeBenefit.Name;
            myEmployeeBenefit.Description = employeeBenefit.Description;

            _employeeBenefitService.UpdateEmployeeBenefit(myEmployeeBenefit);
            return RedirectToAction("ListEmployeeBenefits", new { id = employeeBenefit.EmployeeBenefitId });

        }

        //DELETE
        public ActionResult DeleteEmployeeBenefit(string id)
        {
             var myEmployeeBenefit = _employeeBenefitService.GetEmployeeBenefitById(id);
            var employeeBenefitToDelete = new EmployeeBenefitViewModel
            {
                EmployeeBenefitId = myEmployeeBenefit.EmployeeBenefitId,
                Name = myEmployeeBenefit.Name,
                Description = myEmployeeBenefit.Description
            };
            return View(employeeBenefitToDelete);
        }

        //DELETE
        [HttpPost]
        public ActionResult DeleteEmployeeBenefit(string id, FormCollection formcollection)
        {
            _employeeBenefitService.DeleteEmployeeBenefit(id);
            return RedirectToAction("ListEmployeeBenefits");
        }

    }
}

HrTool.WEB/Views/Registry/CreateDepartment.cshtml
@model HrTool.WEB.Models.DepartmentViewModel

@{
    ViewBag.Title = "CreateDepartment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateDepartment</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DepartmentViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.Employees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EmployeeId, Model.Employees, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Employees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListDepartments")
</div>

HrTool.WEB/Views/Registry/CreateEmployeeBenefit.cshtml
@model HrTool.WEB.Models.EmployeeBenefitViewModel

@{
    ViewBag.Title = "CreateEmployeeBenefit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateEmployeeBenefit</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EmployeeBenefitViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeBenefitId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeBenefitId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeBenefitId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListEmployeeBenefits")
</div>

HrTool.WEB/Views/Registry/DeleteDepartment.cshtml
@model HrTool.WEB.Models.DeleteDepartmentViewModel

@{
    ViewBag.Title = "DeleteDepartment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteDepartment</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeleteDepartmentViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteDepartment", "Registry", FormMethod.Post, new { id = Model.DepartmentId })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListDepartments")
        </div>
    }
</div>

HrTool.WEB/Views/Registry/DeleteEmployeeBenefit.cshtml
@model HrTool.WEB.Models.EmployeeBenefitViewModel

@{
    ViewBag.Title = "DeleteEmployeeBenefit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteEmployeeBenefit</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EmployeeBenefitViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeBenefitId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeBenefitId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListEmployeeBenefits")
        </div>
    }
</div>

HrTool.WEB/Views/Registry/ListDepartments.cshtml
@model IEnumerable<HrTool.WEB.Models.DepartmentViewModel>

@{
    ViewBag.Title = "ListDepartments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListDepartments</h2>

<p>
    @Html.ActionLink("Create New", "CreateDepartment")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentEmail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DepartmentId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeDisplayName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartmentEmail)
        </td>
        <td>
            @Html.ActionLink("Edit", "UpdateDepartment", new { id=item.DepartmentId }) |
            @Html.ActionLink("Delete", "DeleteDepartment", new { id = item.DepartmentId })
        </td>
    </tr>
}

</table>

HrTool.WEB/Views/Registry/ListEmployeeBenefits.cshtml
@model IEnumerable<HrTool.WEB.Models.EmployeeBenefitViewModel>

@{
    ViewBag.Title = "ListEmployeeBenefits";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListEmployeeBenefits</h2>

<p>
    @Html.ActionLink("Create New", "CreateEmployeeBenefit")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeBenefitId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeBenefitId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "UpdateEmployeeBenefit", new { id = item.EmployeeBenefitId }) |
            @Html.ActionLink("Delete", "DeleteEmployeeBenefit", new { id = item.EmployeeBenefitId })
        </td>
    </tr>
}

</table>

HrTool.WEB/Views/Registry/UpdateDepartment.cshtml
@model HrTool.WEB.Models.DepartmentViewModel

@{
    ViewBag.Title = "UpdateDepartment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UpdateDepartment</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DepartmentViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group hidden">
            @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Employees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EmployeeId, Model.Employees, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Employees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListDepartments")
</div>

HrTool.WEB/Views/Registry/UpdateEmployeeBenefit.cshtml
@model HrTool.WEB.Models.EmployeeBenefitViewModel

@{
    ViewBag.Title = "UpdateEmployeeBenefit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UpdateEmployeeBenefit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EmployeeBenefitViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeBenefitId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeBenefitId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeBenefitId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details")
</div>